### ISSUE TITLE
两个版本的网易云音乐解析都有问题

### ISSUE THREAD

**Issue by LiarOnce** [Jrohy/QPlayer-Typecho-Plugin#3]
解析部分单曲时mp3处是空值，没有解析出地址

title:"Tear Rain",artist:"Amateras Records",mp3:"",cover:"http://p4.music.126.net/lSVDA-uyYE_9ju1payCPxA==/6670737046245811.jpg?param=106x106",},

**Comment by Jrohy** [comment]
@LiarOnce 有版权的音乐解析不出地址

**Comment by LiarOnce** [comment]
换了一首一样解析不出来，这次是很冷门的

{title:"Moonlight Sonata (osu!)",artist:"cYsmix",mp3:"",cover:"http://p3.music.126.net/VigdOcu0fnRZC6t4j86bEA==/3394192427248428.jpg?param=106x106",},

**Comment by Jrohy** [comment]
@LiarOnce 换多几首再试试

**Comment by LiarOnce** [comment]
还是没解析出mp3地址，而专辑，艺人，歌单里的都能解析出来

{title:"大鱼",artist:"周深",mp3:"",cover:"http://p3.music.126.net/aiPQXP8mdLovQSrKsM3hMQ==/1416170985079958.jpg?param=106x106",},

{title:"湫兮如风",artist:"徐佳莹",mp3:"",cover:"http://p3.music.126.net/1jo4BLHyhiZb-iL_6qoqmg==/1419469524541522.jpg?param=106x106",},

{title:"让我留在你身边",artist:"陈奕迅",mp3:"",cover:"http://p3.music.126.net/71YQw1K88LS06iMjLRY5CA==/18610333812708195.jpg?param=106x106",},

**Comment by Jrohy** [comment]
@LiarOnce 确实有些单曲不可解析，你可以用idm等工具找出歌曲链接，有空我研究下解析的api

**Comment by Jrohy** [comment]
@LiarOnce 找到歌曲本身所在专辑(用专辑id)即可解析出歌曲链接, 说不定歌单的也行

**Comment by Jrohy** [comment]
@LiarOnce 应该真的是单曲解析失效了，后续版本会取消

**Comment by Jrohy** [comment]
@LiarOnce 网易云方面做解析调整了，必须是国内的ip才能单曲解析，国外的vps都解析不出

**Comment by LiarOnce** [comment]
好吧。。。。。。
